### PR TITLE
nfd-master: fix a crash when processing NodeFeatureRules

### LINKED ISSUE #1170: NFD master panics when no matchFeatures are defined in NodeFeatureRule
**What happened**:

```sh
I0421 13:44:17.450121       1 nfd-master.go:594] will process all nodes in the cluster
panic: assignment to entry in nil map

goroutine 163 [running]:
sigs.k8s.io/node-feature-discovery/pkg/apis/nfd/v1alpha1.(*Features).InsertAttributeFeatures(...)
        /go/node-feature-discovery/pkg/apis/nfd/v1alpha1/feature.go:62
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).processNodeFeatureRule(0xc00080e8c0, 0xc000040720)
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:924 +0x9a9
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).refreshNodeFeatures(0xc00080e8c0, 0x0?, {0xc0007ae180, 0x2f}, 0xc000803360?, 0xc000d65790?, 0x857f38?)
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:746 +0xdc
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).nfdAPIUpdateOneNode(0xc00080e8c0, {0xc0007ae180, 0x2f})
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:675 +0x487
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).nfdAPIUpdateAllNodes(0xc00080e8c0)
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:607 +0x170
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).nfdAPIUpdateHandler(0xc00080e8c0)
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:335 +0x1cc
created by sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).Run
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:225 +0x6fe
```

**What you expected to happen**:

Log error or apply extended resources 😄 

**How to reproduce it (as minimally and precisely as possible)**:

```yaml
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: rdt-l3-closid-extended-rule
spec:
  rules:
    - name: "rdt l3 closid extended rule"
      extendedResources:
        feature.node.kubernetes.io/rdtl3_closid: "@cpu.rdt.RDTL3CA_NUM_CLOSID"
```

I have also tried it with empty list, still panicking:
```yaml
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: rdt-l3-closid-extended-rule
spec:
  rules:
    - name: "rdt l3 closid extended rule"
      extendedResources:
        feature.node.kubernetes.io/rdtl3_closid: "@cpu.rdt.RDTL3CA_NUM_CLOSID"
      matchFeatures: []
```

**Anything else we need to know?**:

Running from `v0.13.0` tag

**Environment**:
- Kubernetes version (use `kubectl version`): 1.23

### PR DESCRIPTION
**Pull request by marquiz**
Fix a a bug where nfd-master with NodeFeature API enabled would crash when NodeFeatureRule objects were processed in the case where no NodeFeature objects existed. This was caused by trying to insert values into a non-initialized NodeFeatureSpec in the code.

This patch adds two safety measures to prevent that from happening in the future. First, add a constructor function for the NodeFeatureSpec type, and second, check for uninitialized object in the function inserting new functions.

TODO: add unit tests for the API helper functions.

Fixes #1170

### CODE REVIEW

File: pkg/apis/nfd/v1alpha1/feature.go [hunk 1]
```diff
@@ -56,7 +65,11 @@ func NewInstanceFeature(attrs map[string]string) *InstanceFeature {
 }
 
 // InsertAttributeFeatures inserts new values into a specific feature.
+// TODO: add unit tests
```
Comment (ArangoGutierrez) [inline pkg/apis/nfd/v1alpha1/feature.go:68]: 😄

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm
