### PR TITLE
fix topology-updater cpu report

### LINKED ISSUE #1978: nfd-topology-updater missed some cpu for Guaranteed pods
**What happened**:
`nfd-topology-updater` is used for report node's NUMA and `Guaranteed` pods's cpu used. But it missed cpu for `Guaranteed` pod which pod's have any no exclusiveCPU.

1. Node `yj-kubevirtwork-001` kubelet config single-numa-node and cpu-manager

```
--cpu-manager-policy=static--topology-manager-policy=single-numa-node
```

I have two pods in node:
```
root@yj-kubevirtmaster-01 ~ # kubectl get po -owide nginx-deployment-68589dd8dc-kzvzh virt-launcher-kubevirttesttest1-p545b
NAME                                    READY   STATUS    RESTARTS   AGE     IP              NODE                  NOMINATED NODE   READINESS GATES
nginx-deployment-68589dd8dc-kzvzh       1/1     Running   0          2d16h   10.106.66.199   yj-kubevirtwork-001   <none>           <none>
virt-launcher-kubevirttesttest1-p545b   3/3     Running   0          4h20m   10.106.66.177   yj-kubevirtwork-001   <none>           1/1
```

In cpu-manager allocated cpu in node
```
cat /var/lib/kubelet/cpu_manager_state | jq
{
  "policyName": "static",
  "defaultCpuSet": "1,3,24-25,48-51,53,55,76-77,100-103",
  "entries": {
    "609526ad-0de0-4543-8188-48f872576fc9": {
      "compute": "26-34,78-86"
    },
    "64dc405a-1a9c-4029-ba5f-778fe5948a10": {
      "compute": "0,2,4-9,52,54,56-61"
    },
    "8310086e-bc8b-4ab3-ac6e-ccc1129fecec": {
      "compute": "35-47,87-99"
    },
    "98f43841-5488-49d7-9f79-29fa68791316": {
      "nginx": "14-15,66-67"
    },
    "b4fd6f12-9cf5-459e-8fdb-3058a2ae22a3": {
      "compute": "10-13,16-23,62-65,68-75"
    }
  },
  "checksum": 2485504922
}
```

But in noderesourcetopologies CR, it only report nginx's CPU set, not report kubevirt-launcher's CPU 
```
kubectl get noderesourcetopologies yj-kubevirtwork-001 -oyaml
apiVersion: topology.node.k8s.io/v1alpha2
attributes:
- name: topologyManagerPolicy
  value: single-numa-node
- name: topologyManagerScope
  value: container
- name: nodeTopologyPodsFingerprint
  value: pfp0v001828baea44880d152
kind: NodeResourceTopology
metadata:
  creationTimestamp: "2024-12-05T13:13:40Z"
  generation: 66528
  name: yj-kubevirtwork-001
  ownerReferences:
  - apiVersion: v1
    kind: Namespace
    name: node-feature-discovery
    uid: 4072a5ce-0634-447e-ab31-dd3f4bc7abac
  resourceVersion: "27862374"
  uid: dd26aaf4-3f38-4708-bb86-89305475a715
topologyPolicies:
- SingleNUMANodeContainerLevel
zones:
- costs:
  - name: node-0
    value: 21
  - name: node-1
    value: 10
  name: node-1
  resources:
  - allocatable: "52"
    available: "52"
    capacity: "52"
    name: cpu
  - allocatable: "201847795712"
    available: "157778243583"
    capacity: "201847795712"
    name: memory
  type: Node
- costs:
  - name: node-0
    value: 10
  - name: node-1
    value: 21
  name: node-0
  resources:
  - allocatable: "50"
    available: "46"
    capacity: "52"
    name: cpu
  - allocatable: "183845359616"
    available: "130691427327"
    capacity: "201130086400"
    name: memory
  type: Node
```

In `nfd-topology-updater` logs: 

```
I1213 06:06:41.791096       1 nfd-topology-updater.go:235] "received updated pod resources" podResources=<
	- Containers:
	  - Name: nginx
	    Resources:
	    - Data:
	      - "66"
	      - "67"
	      - "14"
	      - "15"
	      Name: cpu
	      NumaNodeIds: null
	    - Data:
	      - "8589934592"
	      Name: memory
	      NumaNodeIds:
	      - 0
	  Name: nginx-deployment-68589dd8dc-kzvzh
	  Namespace: default
	- Containers:
	  - Name: compute
	    Resources:
	    - Data:
	      - vhost-net172
	      Name: devices.kubevirt.io/vhost-net
	      NumaNodeIds: null
	    - Data:
	      - kvm760
	      Name: devices.kubevirt.io/kvm
	      NumaNodeIds: null
	    - Data:
	      - tun96
	      Name: devices.kubevirt.io/tun
	      NumaNodeIds: null
	    - Data:
	      - "9141485568"
	      Name: memory
	      NumaNodeIds:
	      - 0
	  - Name: volumecontainerdisk
	    Resources:
	    - Data:
	      - "40000000"
	      Name: memory
	      NumaNodeIds:
	      - 0
	  - Name: guest-console-log
	    Resources:
	    - Data:
	      - "60000000"
	      Name: memory
	      NumaNodeIds:
	      - 0
	  Name: virt-launcher-kubevirttesttest2-8dnfj
	  Namespace: default
 >
```

`nfd-topology-updater` not got kubevirt-launcher pod's compute container's CPU.

**What you expected to happen**:
`nfd-topology-updater` can report all pod container's exclusiveCPU.

**How to reproduce it (as minimally and precisely as possible)**:
For example, create a pod `Pod-a` have 2 containers:

```
containers:
- name: ctr-a
  resources:
    limits:
      cpu: 5   
    requests:
      cpu: 5
- name: ctr-b
  resources:
    limits:
      cpu: 500m
    requests:
      cpu: 500m
```
pod is still a Guaranteed pod , and allocate exclusiveCPU by kubelet's cpu-manager,  but `nfd-topology-updater` will not report it's CPU in topology CR.

**Anything else we need to know?**:
I thought this bug is cause by `hasExclusiveCPUs` func: 

https://github.com/kubernetes-sigs/node-feature-discovery/blob/141607269983adbf13f7f84b3f02314e49c3d278/pkg/resourcemonitor/podresourcesscanner.go#L78-L107

if pod has any container not request cpu as integer, it will return false.

https://github.com/kubernetes-sigs/node-feature-discovery/blob/141607269983adbf13f7f84b3f02314e49c3d278/pkg/resourcemonitor/podresourcesscanner.go#L168-L183

It cause `nfd-topology-updater` skip this pod's all containers loop for report CPU.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by AllenXu93**
Fix #1978

### CODE REVIEW

**Comment by marquiz** [comment]
> While I get again up to speed, do we have test coverage for this change? can we use more unit/e2e tests?

We seem to have some as the tests failed. But yes, we should have specific test case for this scenario-

@AllenXu93 could you fix and update the tests?

**Comment by AllenXu93** [comment]
> > While I get again up to speed, do we have test coverage for this change? can we use more unit/e2e tests?
> 
> 
> 
> We seem to have some as the tests failed. But yes, we should have specific test case for this scenario-
> 
> 
> 
> @AllenXu93 could you fix and update the tests?

ok I will fix in this week

File: pkg/resourcemonitor/podresourcesscanner_test.go [hunk 1]
```diff
@@ -536,6 +548,9 @@ func TestPodScanner(t *testing.T) {
 						},
 					},
 				},
+				Status: corev1.PodStatus{
+					QOSClass: corev1.PodQOSGuaranteed,
```
Comment (marquiz) [inline pkg/resourcemonitor/podresourcesscanner_test.go:552]: Hmm, in real life this pod would be besteffort as it doesn't have any cpu or memory requests/limits. Should the mock pods here be consistent(?) @ffromani thoughts?

Comment (AllenXu93) [reply pkg/resourcemonitor/podresourcesscanner_test.go]: Thanks, this case should not be Guaranteed. I will change the UT code.

File: pkg/resourcemonitor/podresourcesscanner.go [hunk 2]
```diff
@@ -85,9 +85,9 @@ func hasExclusiveCPUs(pod *corev1.Pod) bool {
 			continue
 		}
 		totalCPU += cpuQuantity.Value()
-		isInitContainerGuaranteed := hasIntegralCPUs(pod, &container)
-		if !isInitContainerGuaranteed {
-			return false
+		isInitContainerGuaranteed := hasIntegralCPUs(&container)
```
Comment (ffromani) [inline pkg/resourcemonitor/podresourcesscanner.go:88]: ok, I'm late to the party, but what I'd do is to rewrite `func hasExclusiveCPUs(pod *corev1.Pod) bool` entirely.
A pod gets exclusive cpus iff:
- its QoS is Guaranteed: we should check this inside the function rather than outside, using k8s helpers.
- at least 1 containers of the pod has integral CPU request

in practice this means:
- stop tracking `totalCPU` in this function, we don't need it anymore
- move the `if cpuQuantity, ok = container.Resources.Requests[corev1.ResourceCPU]; !ok` guard inside `hasIntegralCPUs` (arguably if a container requires no CPUs, it has no integral CPUs request...)
- fix unit tests, hopefully few of them

Hopes it makes sense, but I'm convinced this should lead to simpler and less code

Comment (AllenXu93) [reply pkg/resourcemonitor/podresourcesscanner.go:88]: OK, I totally agree with you. The correct way to completely fix this issue is to override the hasExclusiveCPUs method.
I will change it.

**Comment by marquiz** [comment]
Now the unit tests fail

File: pkg/resourcemonitor/podresourcesscanner.go [hunk 3]
```diff
@@ -57,58 +57,49 @@ func NewPodResourcesScanner(namespace string, podResourceClient podresourcesapi.
...
+		return false, false, nil
+	}
+
+	pod, err := resMon.k8sClient.CoreV1().Pods(podResource.Namespace).Get(context.TODO(), podResource.Name, metav1.GetOptions{})
 	if err != nil {
 		return false, false, err
 	}
 
-	isIntegralGuaranteed := hasExclusiveCPUs(pod)
+	podHasExclusiveCPUs := hasExclusiveCPUs(pod)
```
Comment (marquiz) [inline pkg/resourcemonitor/podresourcesscanner.go:72]: nit: somehow this naming makes me confused. `hasExclusiveCPUs(pod)` tells if any containers within has integral cpu requests but doesn't look at the Pod QoS (iow to be correct `hasExclusiveCPUs` would be `hasExclusiveCPUs(pod) && isPodGuaranteed`)

What do you think about renaming a bit like:

```suggestion
	hasIntegralCPUs := podHasIntegralCPUs(pod)
```

Comment (marquiz) [reply pkg/resourcemonitor/podresourcesscanner.go:72]: Oh, looking at @ffromani's earlier comment (https://github.com/kubernetes-sigs/node-feature-discovery/pull/1979#discussion_r1906778199) another possibility (instead of renaming) would be to change `hasExclusiveCPUs(pod)` to behave like it name suggests. That is, check the pods QoS inside the function. Or does this break something elsewhere (non-Guaranteed pods with integral CPUs)(?) Should not afaiu.

Thoughts @ffromani ?

Comment (marquiz) [reply pkg/resourcemonitor/podresourcesscanner.go:72]: ping @AllenXu93 WDYT?

**Comment by AllenXu93** [comment]
@marquiz @ffromani  Sorry to bother you, can you help to review this PR ?

**Comment by marquiz** [comment]
> Sorry to bother you, can you help to review this PR ?

@AllenXu93 any thoughts on these comments?
https://github.com/kubernetes-sigs/node-feature-discovery/pull/1979#discussion_r1925199335

**Comment by AllenXu93** [comment]
> > Sorry to bother you, can you help to review this PR ?
> 
> @AllenXu93 any thoughts on these comments? [#1979 (comment)](https://github.com/kubernetes-sigs/node-feature-discovery/pull/1979#discussion_r1925199335)

The latest code is updated as you suggestion. I rename suggestion

> > Sorry to bother you, can you help to review this PR ?
> 
> @AllenXu93 any thoughts on these comments? [#1979 (comment)](https://github.com/kubernetes-sigs/node-feature-discovery/pull/1979#discussion_r1925199335)

Updated the code just now
 	
```
isIntegralGuaranteed := hasExclusiveCPUs(pod)
```
rename to :
```
isPodHasIntegralCPUs := podHasIntegralCPUs(pod)
```
Do you think these changes ok ?

File: pkg/resourcemonitor/podresourcesscanner.go [hunk 4]
```diff
@@ -57,58 +56,49 @@ func NewPodResourcesScanner(namespace string, podResourceClient podresourcesapi.
...
+		return false, false, nil
+	}
+
+	pod, err := resMon.k8sClient.CoreV1().Pods(podResource.Namespace).Get(context.TODO(), podResource.Name, metav1.GetOptions{})
 	if err != nil {
 		return false, false, err
 	}
 
-	isIntegralGuaranteed := hasExclusiveCPUs(pod)
+	isPodHasIntegralCPUs := podHasIntegralCPUs(pod)
```
Comment (marquiz) [inline pkg/resourcemonitor/podresourcesscanner.go:71]: nit: not a blocker by any means but the name `isPodHas...` is just a funny. Some suggestions for renaming, as the PR needs to be udpated in any case because of build failures

```suggestion
	podHasExclusiveCPUs := checkPodExclusiveCPUs(pod)
```

OR

```suggestion
	podHasExclusiveCPUs := hasExclusiveCPUs(pod)
```

**Review by ffromani — COMMENTED** [review]
sorry it took so long to me. I have mostly minorish comments, once addressed I think LGTM

**Comment by marquiz** [comment]
@ffromani PTAL. I think your review comments have been addressed

**Comment by AllenXu93** [comment]
> New changes are detected. LGTM label has been removed.

@ffromani  Reslove a conflict,  PTAL. 
https://github.com/kubernetes-sigs/node-feature-discovery/pull/1979/commits/5dab33b3ebe0cfd0e53289a4f1bb72a74bd58447

**Comment by ffromani** [comment]
/lgtm

post-rebase change looks minimal and OK

**Comment by marquiz** [comment]
@AllenXu93 could you please rebase the PR and also squash the commits?

**Comment by AllenXu93** [comment]
> @AllenXu93 could you please rebase the PR and also squash the commits?

push again and squash the commits, PTAL
