### PR TITLE
kernel: more agressively sanitize full kernel version

### LINKED ISSUE #390: Regex fails for kernel-version.full on Raspberry Pi nodes
**What happened**:

Error in logs:
2020/11/18 23:39:01 Ignoring invalid feature value kernel-version.full=5.4.51-v8_: [a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')]

Additionally, feature.node.kubernetes.io/kernel-version.full does not get applied to the node

**What you expected to happen**:

Kernel version should be correctly recognized.

**How to reproduce it (as minimally and precisely as possible)**:

My reproduction environment:
- install k3os (k3s mini kubernetes distro) on raspberry pi 4
- install nfd (note: since this is arm64 I cross-compiled the container)
- watch logs

On the host:

\# uname -r
5.4.51-v8+

Specifically, the + on the end of the kernel string gets turned into an _ here
- https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/source/kernel/kernel.go#L115
- fullRegex := regexp.MustCompile("[^-A-Za-z0-9_.]")

Then, the resulting string with a trailing underscore does not meet the required syntax for a feature value.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/arm64"}

- Cloud provider or hardware configuration: raspberry pi 4
- OS (e.g: `cat /etc/os-release`):  VERSION="k3OS v0.11.1"
- Kernel (e.g. `uname -a`): Linux pi4-master 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux

- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

### PR DESCRIPTION
**Pull request by marquiz**
Trim illegal characters from the beginning and end of the kernel version
string. Label values must start and end with an alphanumeric and we want
to have some 'version.full' label, even if a sanitized one.

Fixes #390

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
"agressively" is not a word you want to read on a Monday Morning  :grinning:

**Comment by ArangoGutierrez** [comment]
Prow is not happy :(

**Comment by dbaker-rh** [comment]
+1

is it too late to add a short comment in the code mentioning that characters at the end of labels have different criteria than characters at the start or middle.

It looks like it'll work perfectly; a comment just for future readability.

File: source/kernel/kernel.go [hunk 1]
```diff
@@ -114,6 +114,7 @@ func parseVersion() (map[string]string, error) {
 	// Replace forbidden symbols
 	fullRegex := regexp.MustCompile("[^-A-Za-z0-9_.]")
 	full = fullRegex.ReplaceAllString(full, "_")
+	full = strings.Trim(full, "-_.")
```
Comment (ArangoGutierrez) [inline source/kernel/kernel.go:117]: you need to add `strings` to the imports :)

**Review by ArangoGutierrez — CHANGES_REQUESTED** [review]

File: source/kernel/kernel.go (hunk 1 above)
Comment (marquiz) [reply source/kernel/kernel.go:119]: 😭  I was a bit too quick on this one. Fixed.

**Comment by marquiz** [comment]
> is it too late to add a short comment in the code mentioning that characters at the end of labels have different criteria than characters at the start or middle.

Of course not. I added a short comment, do you think it's enough?

**Comment by dbaker-rh** [comment]
> Of course not. I added a short comment, do you think it's enough?

+1.  lgtm.

**Review by ArangoGutierrez — APPROVED** [review]
/lgtm
