### PR TITLE
nfd-master: fix resync period config option

### LINKED ISSUE #1181: nfd-master: -resync-period has no effect
**What happened**:

The recently added `-resynd-period` flag has no effect, re-labeling of nodes (never) happens.

E.g. running locally, in the example below I'd expecxt `will process all nodes in the cluster` to happen every second, however, nothing happens.

```
$ NODE_NAME=mini-126 ./bin/nfd-master -kubeconfig $HOME/.kube/config -enable-nodefeature-api -resync-period=1s
I0424 14:15:07.622970 1060674 nfd-master.go:185] Node Feature Discovery Master v0.14.0-devel-34-g2356223f
I0424 14:15:07.623004 1060674 nfd-master.go:189] NodeName: "mini-126"
I0424 14:15:07.623010 1060674 nfd-master.go:190] Kubernetes namespace: ""
I0424 14:15:07.623064 1060674 nfd-master.go:1107] config file "/etc/kubernetes/node-feature-discovery/nfd-master.conf" not found, using defaults
I0424 14:15:07.625394 1060674 nfd-master.go:1164] master (re-)configuration successfully completed
I0424 14:15:07.625405 1060674 nfd-master.go:206] starting nfd api controller
I0424 14:15:07.640298 1060674 component.go:36] [core][Server #1] Server created
I0424 14:15:07.640338 1060674 nfd-master.go:299] gRPC server serving on port: 8080
I0424 14:15:07.640394 1060674 component.go:36] [core][Server #1 ListenSocket #2] ListenSocket created
I0424 14:15:08.640929 1060674 nfd-master.go:608] will process all nodes in the cluster
```

**What you expected to happen**:

Nodes would be re-synced/updated periodically, as specified by the `-resync-period` flag

**How to reproduce it (as minimally and precisely as possible)**:

Make sure that CRDs have been deployed and then run locally

```
$ make build
$ $ NODE_NAME=<node-name> ./bin/nfd-master -kubeconfig $HOME/.kube/config -enable-nodefeature-api -resync-period=1s
```

**Anything else we need to know?**:

**Environment**:

Minikube

### PR DESCRIPTION
**Pull request by AhmedGrati**
Resolves #1181.

**How to test:**

Make sure that CRDs have been deployed and then run locally
```bash
make build
NODE_NAME=<node-name> ./bin/nfd-master -kubeconfig $HOME/.kube/config -enable-nodefeature-api -resync-period=1s
```

### CODE REVIEW

File: pkg/nfd-master/nfd-api-controller.go [hunk 1]
```diff
@@ -54,6 +54,8 @@ func newNfdController(config *restclient.Config, nfdApiControllerOptions nfdApiC
 	}
 
 	nfdClient := nfdclientset.NewForConfigOrDie(config)
+	klog.Infof("NFD API controller options: %v", nfdApiControllerOptions)
```
Comment (ArangoGutierrez) [inline pkg/nfd-master/nfd-api-controller.go:57]: Let's put this behind a V
```suggestion
	klog.V(2).Infof("NFD API controller options: %v", nfdApiControllerOptions)
```
having it as regular log would cause too much noice, but is good for debbuging situations

File: pkg/nfd-master/nfd-master.go [hunk 2]
```diff
@@ -1219,3 +1218,19 @@ func (m *nfdMaster) instanceAnnotation(name string) string {
 	}
 	return m.args.Instance + "." + name
 }
+
+func (m *nfdMaster) startNfdControllerApi() error {
```
Comment (ArangoGutierrez) [inline pkg/nfd-master/nfd-master.go:1222]: Could you split this PR into 2, once for just fixing the resync, and a new once with your proposed enhancements, that way the PR/commit show the actual fix and no more.

**Review by ArangoGutierrez — CHANGES_REQUESTED** [review]

File: pkg/nfd-master/nfd-api-controller.go (hunk 1 above)
Comment (marquiz) [reply pkg/nfd-master/nfd-api-controller.go:57]: This is only logged ad startup so V(0) is not so bad but maybe V(1) or V(2) would be better. I also sugges to use `utils.KlogDump` to get well-formatted output

**Review by marquiz — CHANGES_REQUESTED** [review]
Doesn't fix the problem, `-resync-period=1s` still doesn't have any effect

**Comment by marquiz** [comment]
> Doesn't fix the problem, `-resync-period=1s` still doesn't have any effect

Ach, my test setup was broken. Seems to work now

File: pkg/nfd-master/nfd-master.go [hunk 3]
```diff
@@ -1142,6 +1133,13 @@ func (m *nfdMaster) configure(filepath string, overrides string) error {
 	}
 	if m.args.Overrides.ResyncPeriod != nil {
 		c.ResyncPeriod = *m.args.Overrides.ResyncPeriod
+		// restart NFD API controller
+		if m.args.CrdController {
+			err := m.startNfdControllerApi()
+			if err != nil {
+				return nil
+			}
+		}
```
Comment (marquiz) [inline pkg/nfd-master/nfd-master.go:1142]: I'd suggest to move the controller restart out of the `configure()` method, to the mainloop where the config watch event is processed

File: pkg/nfd-master/nfd-master.go [hunk 4]
```diff
@@ -1219,3 +1218,19 @@ func (m *nfdMaster) instanceAnnotation(name string) string {
 	}
 	return m.args.Instance + "." + name
 }
+
+func (m *nfdMaster) startNfdControllerApi() error {
+	kubeconfig, err := m.getKubeconfig()
+	if err != nil {
+		return err
+	}
+	klog.Info("starting nfd api controller")
```
Comment (marquiz) [inline pkg/nfd-master/nfd-master.go:1227]: We also need to stop the previous api controller

**Review by marquiz — COMMENTED** [review]
A few more comments. Please also remove the unused `ResyncPeriod` field from `Args`

**Comment by marquiz** [comment]
Not perfect yet:

```bash
$ NODE_NAME=mini-126 ./bin/nfd-master -kubeconfig $HOME/.kube/config -enable-nodefeature-api -config nfd-master.conf 
I0425 10:07:10.223536 1236969 nfd-master.go:184] Node Feature Discovery Master v0.14.0-devel-37-g3fed5ca5
I0425 10:07:10.223579 1236969 nfd-master.go:188] NodeName: "mini-126"
I0425 10:07:10.223587 1236969 nfd-master.go:189] Kubernetes namespace: ""
I0425 10:07:10.223754 1236969 nfd-master.go:1108] configuration file "nfd-master.conf" parsed
I0425 10:07:10.226718 1236969 nfd-master.go:1163] master (re-)configuration successfully completed
I0425 10:07:10.226731 1236969 nfd-master.go:1227] starting nfd api controller
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ac20f8]

goroutine 1 [running]:
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).startNfdControllerApi(0xc000cb0160)
	/home/marquiz/go/git/node-feature-discovery/review/pkg/nfd-master/nfd-master.go:1230 +0xf8
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).Run(0xc000cb0160)
	/home/marquiz/go/git/node-feature-discovery/review/pkg/nfd-master/nfd-master.go:201 +0x371
main.main()
	/home/marquiz/go/git/node-feature-discovery/review/cmd/nfd-master/main.go:95 +0x47b
```

**Comment by AhmedGrati** [comment]
@marquiz can you please send the content of `nfd-master.conf`?

**Comment by marquiz** [comment]
> @marquiz can you please send the content of `nfd-master.conf`?

```bash
$ cat nfd-master.conf
resyncPeriod: "1s"
```

File: pkg/nfd-master/nfd-master.go (hunk 2 above)
Comment (AhmedGrati) [reply pkg/nfd-master/nfd-master.go:1222]: re-starting the nfd controller API is part of the fix of the resync, and I think extracting the `startNfdControllerApi` in a different method, would remove the redundancy. wdyt?

File: pkg/nfd-master/nfd-master.go [hunk 5]
```diff
@@ -1219,3 +1221,19 @@ func (m *nfdMaster) instanceAnnotation(name string) string {
 	}
 	return m.args.Instance + "." + name
 }
+
+func (m *nfdMaster) startNfdControllerApi() error {
```
Comment (marquiz) [inline pkg/nfd-master/nfd-master.go:1225]: One nit about naming, I'd use name ApiController instead of ControllerApi

```suggestion
func (m *nfdMaster) startNfdApiController() error {
```

File: pkg/nfd-master/nfd-master.go [hunk 6]
```diff
@@ -249,6 +239,17 @@ func (m *nfdMaster) Run() error {
 			if err := m.configure(m.configFilePath, m.args.Options); err != nil {
 				return err
 			}
+
+			// restart NFD API controller
+			if m.nfdController != nil {
+				m.nfdController.stop()
```
Comment (marquiz) [inline pkg/nfd-master/nfd-master.go:245]: Maybe add a log line that we're stopping the controller(?) As we're also logging it being started

**Comment by AhmedGrati** [comment]
Gotta add the e2e tests.

File: pkg/nfd-master/nfd-master.go [hunk 7]
```diff
@@ -249,6 +239,18 @@ func (m *nfdMaster) Run() error {
 			if err := m.configure(m.configFilePath, m.args.Options); err != nil {
 				return err
 			}
+
+			// restart NFD API controller
+			if m.nfdController != nil {
+				klog.V(2).Infof("stopping the nfd controller")
```
Comment (marquiz) [inline pkg/nfd-master/nfd-master.go:245]: For symmetry I'd suggest to use the same log level as in the api controller startup message

File: pkg/nfd-master/nfd-api-controller.go [hunk 8]
```diff
@@ -54,6 +55,8 @@ func newNfdController(config *restclient.Config, nfdApiControllerOptions nfdApiC
 	}
 
 	nfdClient := nfdclientset.NewForConfigOrDie(config)
+	utils.KlogDump(2, "NFD API controller options:", "  ", nfdApiControllerOptions)
```
Comment (marquiz) [inline pkg/nfd-master/nfd-api-controller.go:58]: We need to make the fields in `nfdApiControllerOptions` public so that this dump will print something

**Comment by marquiz** [comment]
> Gotta add the e2e tests.

That would be awesome to keep us safer going forward.

File: pkg/nfd-master/nfd-master.go [hunk 9]
```diff
@@ -249,6 +239,18 @@ func (m *nfdMaster) Run() error {
 			if err := m.configure(m.configFilePath, m.args.Options); err != nil {
 				return err
 			}
+
+			// restart NFD API controller
+			if m.nfdController != nil {
+				klog.Info("stopping the nfd controller")
```
Comment (marquiz) [inline pkg/nfd-master/nfd-master.go:245]: nit: symmetry with the start message

```suggestion
				klog.Info("stopping the nfd api controller")
```

File: test/e2e/node_feature_discovery_test.go [hunk 10]
```diff
@@ -909,6 +909,64 @@ denyLabelNs: []
...
+							nfdv1alpha1.FeatureLabelNs + "/e2e-nodefeature-test-2": "obj-1",
+							nfdv1alpha1.FeatureLabelNs + "/fake-fakefeature3":      "overridden",
+						},
+					}
+					Expect(checkForNodeLabels(ctx, f.ClientSet,
+						expectedLabels, nodes,
+					)).NotTo(HaveOccurred())
+
+					nodeToUpdate := getNode(nodes, targetNodeName)
+					nodeToUpdate.Labels = map[string]string{}
```
Comment (marquiz) [inline test/e2e/node_feature_discovery_test.go:954]: We don't want to delete all labels from the node. Only delete/change those that NFD created. Actually, you don't need to modify the `nodeToUpdate` at all, it's the "original state" of the node so you could just update to this state

Comment (marquiz) [reply test/e2e/node_feature_discovery_test.go:954]: Ach, test fails with `the object has been modified; please apply your changes to the latest version and try again` 🧐 Safest would be patch the object, e.g. modifying some of the created labels.

Anyway, this test is a great addition, not only verifying resync period option but also verifying that nfd actually "fixes" tampered nodes

Comment (AhmedGrati) [reply test/e2e/node_feature_discovery_test.go:954]: the test is actually running in my Minikube cluster... anyway I'll do it the nodes update with the patch

File: test/e2e/node_feature_discovery_test.go [hunk 11]
```diff
@@ -909,6 +909,63 @@ denyLabelNs: []
...
+						},
+					}
+					Expect(checkForNodeLabels(ctx, f.ClientSet,
+						expectedLabels, nodes,
+					)).NotTo(HaveOccurred())
+
+					nodeToUpdate := getNode(nodes, targetNodeName)
+					nodeToUpdate.Labels[nfdv1alpha1.FeatureLabelNs+"/e2e-nodefeature-test-1"] = "randomValue"
+
+					Expect(err).NotTo(HaveOccurred())
```
Comment (marquiz) [inline test/e2e/node_feature_discovery_test.go:956]: No wonder the test passes as the node is not updated at all. I still remain that we should patch the node. Otherwise the test will be flaky at best

**Comment by marquiz** [comment]
You probably didn't actually run the test as they fail with

```
  [FAILED] Unexpected error:
      <*errors.StatusError | 0xc0004ad860>: 
      the server rejected our request due to an error in our request
      {
          ErrStatus: 
              code: 422
              details: {}
              message: the server rejected our request due to an error in our request
              metadata: {}
              reason: Invalid
              status: Failure,
      }
  occurred
```

File: test/e2e/node_feature_discovery_test.go [hunk 12]
```diff
@@ -909,6 +910,74 @@ denyLabelNs: []
...
+
+					nodeToUpdate := getNode(nodes, targetNodeName)
+					err = k8sHelper.PatchNode(k8sClient, nodeToUpdate.Name, []apihelper.JsonPatch{
+						{
+							Op:    "replace",
+							Value: "randomValue",
+							Path:  "/metadata/labels/" + nfdv1alpha1.FeatureLabelNs + "/e2e-nodefeature-test-1",
+						},
+					})
+					Expect(err).NotTo(HaveOccurred())
```
Comment (marquiz) [inline test/e2e/node_feature_discovery_test.go:968]: The apihelper type is pretty useless here. Just use the available clientset directly. Also, use NewJsonPatch helper to get correctly formatted patch that applies to the node

```suggestion
                                        data, err := json.Marshal(apihelper.NewJsonPatch("replace", "/metadata/labels/", nfdv1alpha1.Featur
eLabelNs+"/e2e-nodefeature-test-1", "randomValue"))
                                        Expect(err).NotTo(HaveOccurred())
                                        _, err = f.ClientSet.CoreV1().Nodes().Patch(ctx, targetNodeName, types.JSONPatchType, data, metav1.
PatchOptions{})
                                        Expect(err).NotTo(HaveOccurred())

```

**Comment by AhmedGrati** [comment]
> You probably didn't actually run the test as they fail with
> 
> ```
>   [FAILED] Unexpected error:
>       <*errors.StatusError | 0xc0004ad860>: 
>       the server rejected our request due to an error in our request
>       {
>           ErrStatus: 
>               code: 422
>               details: {}
>               message: the server rejected our request due to an error in our request
>               metadata: {}
>               reason: Invalid
>               status: Failure,
>       }
>   occurred
> ```

Yes I did, they passed successfully on my local machine. It's minikube cluster on top of arm64 macos.

**Comment by marquiz** [comment]
> Yes I did, they passed successfully on my local machine. It's minikube cluster on top of arm64 macos.

Ypu prolly tested something else 😇 It cannot pass as the patch is incorrectly formatted (`reason: Invalid`)

File: test/e2e/node_feature_discovery_test.go [hunk 13]
```diff
@@ -909,6 +912,73 @@ denyLabelNs: []
...
+								"replace",
+								"/metadata/labels",
+								nfdv1alpha1.FeatureLabelNs+"/e2e-nodefeature-test-1",
+								"randomValue",
+							),
+						},
+					)
+					Expect(err).NotTo(HaveOccurred())
+
+					_, err = f.ClientSet.CoreV1().Nodes().Patch(context.TODO(), targetNodeName, types.JSONPatchType, patches, metav1.PatchOptions{})
```
Comment (marquiz) [inline test/e2e/node_feature_discovery_test.go:968]: Let's use proper context as we have one
```suggestion
					_, err = f.ClientSet.CoreV1().Nodes().Patch(ctx, targetNodeName, types.JSONPatchType, patches, metav1.PatchOptions{})
```

**Review by marquiz — APPROVED** [review]
Thx for fixing the issue and adding tests @AhmedGrati! I would be good to merge this

**Review by marquiz — APPROVED** [review]
Thanks @AhmedGrati 🙏

/retitle nfd-master: fix resync period config option

One more ask: could you rebase on top of the latest master? Not related to this PR but we'd like to test the codecov reporting 🥸

**Comment by AhmedGrati** [comment]
> Thanks @AhmedGrati 🙏
> 
> /retitle nfd-master: fix resync period config option
> 
> One more ask: could you rebase on top of the latest master? Not related to this PR but we'd like to test the codecov reporting 🥸

Done 👌

**Comment by marquiz** [comment]
Sorry @AhmedGrati, one more rebase needed, not because of this PR (it is solid) but because of the codecov mess we've created 🙈
/unhold

**Comment by marquiz** [comment]
Thx @AhmedGrati !
/assign @ArangoGutierrez

**Comment by ArangoGutierrez** [comment]
it fails to me 
```bash
I0428 18:36:16.513067       1 nfd-master.go:610] will process all nodes in the cluster
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1abc1e8]

goroutine 121 [running]:
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).nfdAPIUpdateOneNode(0xc000143e00, {0xc000a83578, 0x8})
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:633 +0x108
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).nfdAPIUpdateAllNodes(0xc000143e00)
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:623 +0x170
sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).nfdAPIUpdateHandler(0xc000143e00)
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:346 +0x1cc
created by sigs.k8s.io/node-feature-discovery/pkg/nfd-master.(*nfdMaster).Run
        /go/node-feature-discovery/pkg/nfd-master/nfd-master.go:224 +0x53c
```

after editing the configMap to 1s, and waiting a couple seconds

**Comment by ArangoGutierrez** [comment]
`kubectl edit cm -n node-feature-discovery nfd-master-conf`

**Comment by AhmedGrati** [comment]
Sorry @ArangoGutierrez but I tried to reproduce it on my local machine using tilt, but I had this error during the `go install`:
```
→ ../pkg/mod/k8s.io/apiserver@v0.27.1/pkg/authentication/token/cache/cached_token_authenticator.go:286:29: undefined: unsafe.StringData
→ ../pkg/mod/k8s.io/apiserver@v0.27.1/pkg/authentication/token/cache/cached_token_authenticator.go:297:16: undefined: unsafe.String
→ ../pkg/mod/k8s.io/apiserver@v0.27.1/pkg/authentication/token/cache/cached_token_authenticator.go:297:30: undefined: unsafe.SliceData
```
However, I depleted a `NodeFeatureRule` and I ran:
```
NODE_NAME=minikube ./bin/nfd-master -kubeconfig $HOME/.kube/config -enable-nodefeature-api -config nfd-master.conf
```
and I updated the `nfd-master-conf`, but there's no error.
Any kind of help to reproduce it would be much appreciated.

**Comment by ArangoGutierrez** [comment]
> Sorry @ArangoGutierrez but I tried to reproduce it on my local machine using tilt, but I had this error during the `go install`:
> 
> ```
> → ../pkg/mod/k8s.io/apiserver@v0.27.1/pkg/authentication/token/cache/cached_token_authenticator.go:286:29: undefined: unsafe.StringData
> → ../pkg/mod/k8s.io/apiserver@v0.27.1/pkg/authentication/token/cache/cached_token_authenticator.go:297:16: undefined: unsafe.String
> → ../pkg/mod/k8s.io/apiserver@v0.27.1/pkg/authentication/token/cache/cached_token_authenticator.go:297:30: undefined: unsafe.SliceData
> ```
> 
> However, I depleted a `NodeFeatureRule` and I ran:
> 
> ```
> NODE_NAME=minikube ./bin/nfd-master -kubeconfig $HOME/.kube/config -enable-nodefeature-api -config nfd-master.conf
> ```
> 
> and I updated the `nfd-master-conf`, but there's no error. Any kind of help to reproduce it would be much appreciated.


I am running  `make IMAGE_TAG_NAME=pr_1185 image push deploy` 
and then editing the configmap, I an not running it local, maybe that's the diff

**Comment by AhmedGrati** [comment]
@ArangoGutierrez I'm investigating it.

**Comment by AhmedGrati** [comment]
@ArangoGutierrez the problem is that because you ran it without using the `-enable-nodefeature-api` flag, that's why it's crashing. So it should be fixed, but I'm not sure that it's related to this PR. wdyt?

**Comment by marquiz** [comment]
Thanks @ArangoGutierrez for reporting this segfault.

> the problem is that because you ran it without using the `-enable-nodefeature-api` flag, that's why it's crashing. So it should be fixed, but I'm not sure that it's related to this PR. Even on the master branch, u can reproduce it, so I assume we should fix it in another PR. wdyt?

We should never crash like this. It's related to the dynamic resync-period setting so I think it should be fixed in this PR. I guess the most straightforward fix would be to just add additional check for `m.args.EnableNodeFeatureApi` before signaling the the "update all" channel. Probably better would be to have safeguard e.g. in `nfdAPIUpdateHandler`.

**Comment by marquiz** [comment]
looks good to me, ping @ArangoGutierrez

**Review by ArangoGutierrez — CHANGES_REQUESTED** [review]
```bash
0502 18:10:23.985214       1 nfd-master.go:590] received labeling request for node "minikube"
I0502 18:11:11.463236       1 nfd-master.go:238] reloading configuration
I0502 18:11:11.463507       1 nfd-master.go:1119] configuration file "/etc/kubernetes/node-feature-discovery/nfd-master.conf" parsed
I0502 18:11:11.463561       1 nfd-master.go:1167] master (re-)configuration successfully completed
I0502 18:11:11.463626       1 nfd-master.go:245] stopping the nfd api controller
I0502 18:11:11.463647       1 nfd-master.go:1231] starting nfd api controller
I0502 18:11:23.952276       1 nfd-master.go:590] received labeling request for node "minikube"
I0502 18:12:23.973806       1 nfd-master.go:590] received labeling request for node "minikube"
```
